trigger:
  branches:
    include:
      - main # Adjust based on your branch naming convention

pool:
  name: Default

variables:
  NODE_ENV: 'production'
  buildArtifactName: 'node-app'


steps:
  - task: NodeTaskRunnerInstaller@0
    inputs: 
      nodeVersion: '6'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build
    displayName: 'npm build'
 