trigger:
  branches:
    include:
      - main # Adjust based on your branch naming convention

pool:
  vmImage: Default

variables:
  NODE_ENV: 'production'
  buildArtifactName: 'node-app'

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: 'BuildJob'
        displayName: 'Build'
        steps:
          - task: UseNode@1
            inputs:
              version: '16.x'
              

  - stage: Install
    displayName: 'Install'
    jobs:
      - job: 'BuildJob'
        displayName: 'Build'
        steps:
          - script: |
              npm install
            displayName: Install Dependencies

           
  - stage: RunBuild
    displayName: 'Run build'
    jobs:
      - job: 'BuildJob'
        displayName: 'Build'
        steps:
          - script: |
              npm run build
            displayName: Compile Project
              